version: '3.7'

services:
  nginx:
    depends_on:
      - php
    image: nginx:latest
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/app:rw
    ports:
      - '80:80'
  php:
    depends_on:
      - composer
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: dev
    volumes:
      - .:/app:rw
      - ./docker/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf

  mysql:
    image: mysql:5.7
    volumes:
      -   synega-data:/var/lib/mysql
      - ./docker/logs/mysql:/var/log/mysql
      - ./docker/mysql/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=william
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"

  composer:
    build:
      context: .
      dockerfile: docker/composer/Dockerfile
      target: vendor
    volumes:
      - .:/app:rw

volumes:
  synega-data:
